### ISSUE TITLE
Installation from GitHub

### ISSUE THREAD

**Issue by rgieseke** [ISI-MIP/isipedia-author#3]
I think the installation can be simplified by putting

```
pip install git+https://github.com/ISI-MIP/isipedia-library
```

for the isipedia library ...

**Comment by perrette** [comment]
The thing I do not like about that method is that it clones the whole repo anew to a tmp directory prior to doing the install. That is why I indicated the git clone command in the readme. It is temporary, until we have a tarball to point to (i.e. until we issue a specific version to work with). Let's say all these things will be operational when the website is online.

**Comment by perrette** [comment]
But ok I see advantage of using pip. Using `python setup.py install` followed by pip install leads to:
```
ERROR: Cannot uninstall 'Isipedia-Library'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
i.e. pip machinery is hindered by previous direct install.

**Comment by perrette** [comment]
Closing now because radical new structuring and use of this repo. Ok that I use your [ice cream example](examples)?

**Comment by rgieseke** [comment]
Sure!

**Comment by perrette** [comment]
I really like it :)
